#!/usr/bin/env python3
"""
Generates the Number interesting facts launcher icon from one geometry definition:
  - adaptive icon layers (vector drawables) + monochrome layer for themed icons
  - legacy mipmap PNGs, the 512x512 Google Play icon and a preview sheet (Pillow)

Original artwork: a magnifying glass with a number sign (#) in its lens, on a dark-teal
graph-paper background, in the app's colours. Coordinates use the 108x108 adaptive-icon canvas;
all foreground artwork stays inside the 66-unit safe circle (radius 33 around 54,54).

Usage: python3 tools/icon/generate_icon.py <project-root> <preview-out-dir>
Requires Pillow (pip install pillow).
"""
import math
import os
import sys

from PIL import Image, ImageDraw

# ---- palette (from values-night/colors.xml / values/colors.xml) ----
BG = (0x0A, 0x43, 0x36)            # dark teal
GRID = (0x6C, 0xDB, 0xAE, 0x2E)    # mint, ~18 % alpha
MINT = (0x89, 0xF8, 0xC9)          # md_primary_container (light scheme)
LENS_FILL = (0x89, 0xF8, 0xC9, 0x24)

# ---- geometry (108-unit canvas) ----
CX = CY = 54.0
SAFE_R = 33.0
LENS = (48.0, 48.0)
RING_OUT, RING_IN = 20.0, 14.5
HANDLE_END = (70.5, 70.5)
HANDLE_HALF = 3.8                  # half thickness, round caps
HASH_BAR = 4.0                     # bar thickness
HASH_LEN = 20.6                    # bar length
HASH_OFF = 4.3                     # bar centre offset from lens centre
HASH_R = 1.8                       # bar corner radius
GRID_STEP = 9.0
GRID_W = 0.6


def handle_start():
    a = math.radians(45)
    return (LENS[0] + RING_OUT * math.cos(a) - 1.0, LENS[1] + RING_OUT * math.sin(a) - 1.0)


def hash_bars():
    """(left, top, right, bottom) of the four bars."""
    x, y = LENS
    h = HASH_LEN / 2
    t = HASH_BAR / 2
    bars = []
    for dx in (-HASH_OFF, HASH_OFF):   # vertical bars
        bars.append((x + dx - t, y - h, x + dx + t, y + h))
    for dy in (-HASH_OFF, HASH_OFF):   # horizontal bars
        bars.append((x - h, y + dy - t, x + h, y + dy + t))
    return bars


def handle_polygon():
    (x0, y0), (x1, y1) = handle_start(), HANDLE_END
    dx, dy = x1 - x0, y1 - y0
    n = math.hypot(dx, dy)
    px, py = -dy / n * HANDLE_HALF, dx / n * HANDLE_HALF
    return [(x0 + px, y0 + py), (x1 + px, y1 + py), (x1 - px, y1 - py), (x0 - px, y0 - py)]


# ---- safe-area check ----
def check_safe_area():
    far = [math.hypot(LENS[0] - CX, LENS[1] - CY) + RING_OUT,
           math.hypot(HANDLE_END[0] - CX, HANDLE_END[1] - CY) + HANDLE_HALF]
    for l, t, r, b in hash_bars():
        for px, py in ((l, t), (r, t), (l, b), (r, b)):
            far.append(math.hypot(px - CX, py - CY))
            assert math.hypot(px - LENS[0], py - LENS[1]) < RING_IN, "# touches the ring"
    worst = max(far)
    assert worst <= SAFE_R, f"artwork reaches {worst:.2f} > safe radius {SAFE_R}"
    return worst


# ---- vector drawables ----
def f(v):
    return f"{v:.2f}".rstrip("0").rstrip(".")


def circle_path(cx, cy, r):
    return (f"M{f(cx - r)},{f(cy)} a{f(r)},{f(r)} 0 1,0 {f(2 * r)},0 "
            f"a{f(r)},{f(r)} 0 1,0 {f(-2 * r)},0 Z")


def rrect_path(l, t, r, b, rad):
    w, h = r - l, b - t
    return (f"M{f(l + rad)},{f(t)} h{f(w - 2 * rad)} a{f(rad)},{f(rad)} 0 0 1 {f(rad)},{f(rad)} "
            f"v{f(h - 2 * rad)} a{f(rad)},{f(rad)} 0 0 1 {f(-rad)},{f(rad)} h{f(-(w - 2 * rad))} "
            f"a{f(rad)},{f(rad)} 0 0 1 {f(-rad)},{f(-rad)} v{f(-(h - 2 * rad))} "
            f"a{f(rad)},{f(rad)} 0 0 1 {f(rad)},{f(-rad)} Z")


def poly_path(pts):
    return "M" + " L".join(f"{f(x)},{f(y)}" for x, y in pts) + " Z"


def hexc(rgb, alpha=None):
    a = rgb[3] if len(rgb) == 4 else (alpha if alpha is not None else 0xFF)
    return "#%02X%02X%02X%02X" % (a, rgb[0], rgb[1], rgb[2])


HEADER = ('<?xml version="1.0" encoding="utf-8"?>\n'
          '<!-- Generated by tools/icon/generate_icon.py: original artwork for Number interesting facts. -->\n'
          '<vector xmlns:android="http://schemas.android.com/apk/res/android"\n'
          '    android:width="108dp"\n    android:height="108dp"\n'
          '    android:viewportWidth="108"\n    android:viewportHeight="108">\n')


def path_xml(d, color, even_odd=False):
    fill = '\n        android:fillType="evenOdd"' if even_odd else ""
    return f'    <path\n        android:fillColor="{color}"{fill}\n        android:pathData="{d}" />\n'


def foreground_paths(mono):
    ring = circle_path(*LENS, RING_OUT) + " " + circle_path(*LENS, RING_IN)
    handle = poly_path(handle_polygon()) + " " + circle_path(*HANDLE_END, HANDLE_HALF)
    bars = " ".join(rrect_path(*b, HASH_R) for b in hash_bars())
    color = "#FFFFFFFF" if mono else hexc(MINT)
    out = ""
    if not mono:
        out += path_xml(circle_path(*LENS, RING_IN), hexc(LENS_FILL))
    out += path_xml(ring, color, even_odd=True)
    out += path_xml(handle, color)
    out += path_xml(bars, color)
    return out


def background_xml():
    lines = []
    v = GRID_STEP
    while v < 108:
        lines.append(f"M{f(v)},0 L{f(v)},108 M0,{f(v)} L108,{f(v)}")
        v += GRID_STEP
    grid = " ".join(lines)
    return (HEADER + path_xml("M0,0 H108 V108 H0 Z", hexc(BG))
            + f'    <path\n        android:strokeColor="{hexc(GRID)}"\n        android:strokeWidth="{f(GRID_W)}"\n'
              f'        android:pathData="{grid}" />\n</vector>\n')


# ---- raster rendering ----
def render_layer(size, draw_fn, crop):
    """Render the 108-unit canvas region `crop` (l, t, r, b) into size x size, supersampled."""
    ss = 4
    big = size * ss
    l, t, r, b = crop
    s = big / (r - l)

    def P(x, y):
        return ((x - l) * s, (y - t) * s)

    img = Image.new("RGBA", (big, big), (0, 0, 0, 0))
    draw_fn(img, P, s)
    return img.resize((size, size), Image.LANCZOS)


def draw_background(img, P, s):
    d = ImageDraw.Draw(img)
    d.rectangle([0, 0, img.width, img.height], fill=BG + (255,))
    layer = Image.new("RGBA", img.size, (0, 0, 0, 0))
    ld = ImageDraw.Draw(layer)
    v = GRID_STEP
    while v < 108:
        ld.line([P(v, 0), P(v, 108)], fill=GRID, width=max(1, round(GRID_W * s)))
        ld.line([P(0, v), P(108, v)], fill=GRID, width=max(1, round(GRID_W * s)))
        v += GRID_STEP
    img.alpha_composite(layer)


def draw_foreground(img, P, s, mono=False, color=None):
    col = (color or ((255, 255, 255) if mono else MINT)) + (255,)
    layer = Image.new("RGBA", img.size, (0, 0, 0, 0))
    d = ImageDraw.Draw(layer)
    cx, cy = P(*LENS)
    if not mono:
        fill = Image.new("RGBA", img.size, (0, 0, 0, 0))
        ImageDraw.Draw(fill).ellipse([cx - RING_IN * s, cy - RING_IN * s, cx + RING_IN * s, cy + RING_IN * s],
                                     fill=LENS_FILL)
        img.alpha_composite(fill)
    d.ellipse([cx - RING_OUT * s, cy - RING_OUT * s, cx + RING_OUT * s, cy + RING_OUT * s], fill=col)
    d.ellipse([cx - RING_IN * s, cy - RING_IN * s, cx + RING_IN * s, cy + RING_IN * s], fill=(0, 0, 0, 0))
    d.polygon([P(*p) for p in handle_polygon()], fill=col)
    ex, ey = P(*HANDLE_END)
    d.ellipse([ex - HANDLE_HALF * s, ey - HANDLE_HALF * s, ex + HANDLE_HALF * s, ey + HANDLE_HALF * s], fill=col)
    for l, t, r, b in hash_bars():
        (x0, y0), (x1, y1) = P(l, t), P(r, b)
        d.rounded_rectangle([x0, y0, x1, y1], radius=HASH_R * s, fill=col)
    img.alpha_composite(layer)


VISIBLE = (18, 18, 90, 90)   # what launchers show of the 108 canvas (72 units)


def full_icon(size, crop=VISIBLE):
    img = render_layer(size, draw_background, crop)
    img.alpha_composite(render_layer(size, lambda i, P, s: draw_foreground(i, P, s), crop))
    return img


def mask(img, shape):
    size = img.width
    ss = 4
    m = Image.new("L", (size * ss, size * ss), 0)
    d = ImageDraw.Draw(m)
    if shape == "circle":
        d.ellipse([0, 0, size * ss - 1, size * ss - 1], fill=255)
    elif shape == "rounded":
        d.rounded_rectangle([0, 0, size * ss - 1, size * ss - 1], radius=size * ss * 0.22, fill=255)
    elif shape == "square":
        d.rounded_rectangle([0, 0, size * ss - 1, size * ss - 1], radius=size * ss * 0.09, fill=255)
    m = m.resize((size, size), Image.LANCZOS)
    out = Image.new("RGBA", (size, size), (0, 0, 0, 0))
    out.paste(img, (0, 0), m)
    return out


def write(path, text):
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(text)


def main():
    root, preview_dir = sys.argv[1], sys.argv[2]
    worst = check_safe_area()
    res = os.path.join(root, "app/src/main/res")

    write(os.path.join(res, "drawable/ic_launcher_background.xml"), background_xml())
    write(os.path.join(res, "drawable/ic_launcher_foreground.xml"), HEADER + foreground_paths(False) + "</vector>\n")
    write(os.path.join(res, "drawable/ic_launcher_monochrome.xml"), HEADER + foreground_paths(True) + "</vector>\n")
    adaptive = ('<?xml version="1.0" encoding="utf-8"?>\n'
                '<adaptive-icon xmlns:android="http://schemas.android.com/apk/res/android">\n'
                '    <background android:drawable="@drawable/ic_launcher_background" />\n'
                '    <foreground android:drawable="@drawable/ic_launcher_foreground" />\n'
                '    <monochrome android:drawable="@drawable/ic_launcher_monochrome" />\n'
                '</adaptive-icon>\n')
    write(os.path.join(res, "mipmap-anydpi/ic_launcher.xml"), adaptive)
    write(os.path.join(res, "mipmap-anydpi/ic_launcher_round.xml"), adaptive)

    # Legacy raster icons (fallback resources; Android 8.0+ launchers use the adaptive icon).
    for dens, px in (("mdpi", 48), ("hdpi", 72), ("xhdpi", 96), ("xxhdpi", 144), ("xxxhdpi", 192)):
        d = os.path.join(res, f"mipmap-{dens}")
        os.makedirs(d, exist_ok=True)
        base = full_icon(px)
        mask(base, "square").save(os.path.join(d, "ic_launcher.png"), optimize=True)
        mask(base, "circle").save(os.path.join(d, "ic_launcher_round.png"), optimize=True)

    # Google Play: 512x512 full square (Play applies its own corner mask), 32-bit PNG.
    play_dir = os.path.join(root, "docs/store-assets")
    os.makedirs(play_dir, exist_ok=True)
    full_icon(512).save(os.path.join(play_dir, "play-icon-512.png"), optimize=True)

    # Preview sheet.
    os.makedirs(preview_dir, exist_ok=True)
    W, H = 1400, 1200
    sheet = Image.new("RGBA", (W, H), (245, 247, 245, 255))
    d = ImageDraw.Draw(sheet)
    dark = Image.new("RGBA", (W, H - 780), (18, 22, 20, 255))
    sheet.alpha_composite(dark, (0, 780))
    big = full_icon(288)
    x = 60
    for shape in ("circle", "rounded", "square"):
        sheet.alpha_composite(mask(big, shape), (x, 60))
        x += 330
    # full 108 canvas with safe circle, to show the mask safe area
    canvas = full_icon(288, crop=(0, 0, 108, 108))
    cd = ImageDraw.Draw(canvas)
    k = 288 / 108
    cd.rectangle([18 * k, 18 * k, 90 * k, 90 * k], outline=(255, 120, 120, 255), width=2)
    cd.ellipse([(54 - 33) * k, (54 - 33) * k, (54 + 33) * k, (54 + 33) * k], outline=(255, 210, 90, 255), width=2)
    sheet.alpha_composite(canvas, (x + 30, 60))
    # small sizes on light and dark
    for row, y in ((0, 420), (1, 870)):
        x = 60
        for px in (192, 96, 72, 48, 36, 24):
            sheet.alpha_composite(mask(full_icon(px), "circle"), (x, y))
            x += px + 40
        # themed (monochrome) examples
        tint_bg, tint_fg = ((0xDF, 0xE8, 0xE2), (0x1F, 0x35, 0x2B)) if row == 0 else ((0x25, 0x2B, 0x28), (0xB3, 0xCC, 0xBE))
        for px in (96, 48):
            m = Image.new("RGBA", (px, px), tint_bg + (255,))
            m.alpha_composite(render_layer(px, lambda i, P, s: draw_foreground(i, P, s, mono=True, color=tint_fg), VISIBLE))
            sheet.alpha_composite(mask(m, "circle"), (x, y))
            x += px + 40
    d = ImageDraw.Draw(sheet)
    d.text((60, 20), "Adaptive masks: circle / rounded square / square  |  108-unit canvas: red = visible 72, yellow = 66 safe circle",
           fill=(40, 40, 40, 255))
    d.text((60, 390), "Sizes 192 / 96 / 72 / 48 / 36 / 24 px, then themed (monochrome) 96 / 48 px - light background",
           fill=(40, 40, 40, 255))
    d.text((60, 830), "Same on a dark background", fill=(220, 220, 220, 255))
    sheet.convert("RGB").save(os.path.join(preview_dir, "icon-preview.png"), optimize=True)
    print(f"ok: artwork max radius {worst:.2f} of safe {SAFE_R}")


if __name__ == "__main__":
    main()
